name: Отмена предыдущих тестов
on:
  push:
    branches:
      - master

jobs:
  Cancel:
    name: 'Отмена Ненужных Билдов'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7
        with:
          workflow_id: 9143745, 5560543
          access_token: ${{ github.token }}
